config/routes.rb
Rails.application.routes.draw do
  root to: 'pokemons#index'
  resources :pokemons, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evolution_chain.rb
class EvolutionChain < ApplicationRecord
  has_many :pokemons
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_types
  has_many :types, through: :pokemon_types
  belongs_to :evolution_chain, optional: true

  def self.filter_by_name(name)
    sql_query = "pokemons.name ILIKE :name"
    return Pokemon.where(sql_query, name: "%#{name}%").order(:id)
  end

  def self.filter_by_type(type)
    return Type.find_by(name: type).pokemons
  end

  def self.filter_by_name_and_type(name, type)
    sql_query = "pokemons.name ILIKE :name"
    return Type.find_by(name: type).pokemons.where(sql_query, name: "%#{name}%").order(:id)
  end

  def evolution
    evolution_chain = {first: [], second: [], third: []}
    self.evolution_chain.chain.each do |key, pokemon_array_in_level|
      if pokemon_array_in_level.present?
        pokemon_array_in_level.each do |species_name|
          evolution_chain[key.to_sym] << Pokemon.find_by(species: species_name)
        end
      end
    end
    return evolution_chain
  end
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show]
  def index
    if params[:search].present?
      name = params[:search]["name"]
      type = params[:search]["type"]
      if name.present? && type.present?
        @pokemons = Pokemon.filter_by_name_and_type(name, type)
      elsif type.present?
        @pokemons = Pokemon.filter_by_type(type)
      elsif name.present?
        @pokemons = Pokemon.filter_by_name(name)
      else
        @pokemons = Pokemon.all
      end
    else
      @pokemons = Pokemon.all
    end
  end

  def show
    @evolution_chain = @pokemon.evolution
  end

  private

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokedexWotdrms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'partials/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_card.html.erb
<div class="card">
  <div class="heart-container">
    <i id="pokemon-id-<%= @pokemon.id%>" class="button-toggle-favorite far fa-heart index-heart" data-pokemon-id="<%= @pokemon.id%>"></i>
  </div>
  <%= link_to pokemon_path(@pokemon) do %>
    <%= image_tag "#{@pokemon.sprite_url}", class: "card-sprite" %>
    <div class="card-name">
      <%= @pokemon.name.capitalize %>
    </div>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-disco-pokedex">
  <%= link_to root_path, class: "navbar-brand" do%>
    <%= image_tag "pokeball" , class: "fa-home"%>
  <% end %>
  <div id='pokemon-search'>
    <%= simple_form_for :search, method: :get, url: :pokemons, wrapper: :inline_form, html: {class: ""} do |f| %>
      <%= f.input :name, as: :string, input_html: { class: "form-inline", id:"name-input-field" }, placeholder: "Find Pokemon" %>
      <%= f.input :type, as: :select, :collection => ["normal", "fighting", "flying", "poison", "ground", "rock", "bug", "ghost", "steel", "fire", "water", "grass", "electric", "psychic", "ice", "dragon", "dark", "fairy"].sort, input_html: { class: "form-inline", id: "type-select-field" }, prompt: "Type" %>
      <%= f.submit "Filter", class: "btn btn-warning form-inline" %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "https://github.com/Disco-Chef/pokedex-wotdrms", class: "fav-button nav-link" do %>
          <i class="fab fa-github-square"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/partials/_showcase.html.erb
<div id="sprite-half">
  <%= image_tag "#{@pokemon.sprite_url}", id: "showcase-sprite" %>
</div>
<div id="name-area">
  <%= link_to "#{pokemon_path(@pokemon.id - 1)}" do %>
    <i class="fas fa-angle-double-left double-arrows" ></i>
  <% end %>
  <div id="pokemon-name">
    <%= @pokemon.name.capitalize %>
  </div>
  <%= link_to "#{pokemon_path(@pokemon.id + 1)}" do %>
    <i class="fas fa-angle-double-right double-arrows" ></i>
  <% end %>
</div>
<div id="types-row">
  <div id="pokemon-types">
    <div class="type" id="<%= @pokemon.types.first.name %>">
      <%= link_to @pokemon.types.first.name.capitalize, pokemons_path(search: {"name" => nil, "type" => @pokemon.types.first.name})  %>
    </div>
    <% if @pokemon.types.count > 1 %>
      <div class="type" id="<%= @pokemon.types.last.name %>">
        <%= link_to @pokemon.types.last.name.capitalize, pokemons_path(search: {"name" => nil, "type" => @pokemon.types.last.name})  %>
      </div>
    <% end %>
  </div>
  <i id="pokemon-id-<%= @pokemon.id %>" data-pokemon-id="<%= @pokemon.id %>" class="button-toggle-favorite far fa-heart showcase-heart"></i>
</div>

<div id="pokemon-info">
  <div id="pokemon-description">
    <%= @pokemon.description %>
  </div>
  
  <div id="pokemon-stats">
    <div class="half-side">
      <div class="stat-container">
        <i class="fas fa-heartbeat"></i>
        <div class="stat hp"><%= @pokemon.hp %></div>
      </div>
      <div class="stat-container">
        <%= image_tag "swords.png" , class: "swords"%>
        <div class="stat atk"><%= @pokemon.attack %></div>
      </div>
      <div class="stat-container">
        <i class="fas fa-shield-alt"></i>
        <div class="stat def"><%= @pokemon.defense %></div>
      </div>
    </div>
    
    <div class="half-side">
      <div class="stat-container">
        <div class="special-stats">
          <i class="fas fa-star"></i><%= image_tag "swords" , class: "swords"%>
        </div>
        <div class="stat sp-atk"><%= @pokemon.special_attack %></div>
      </div>
      <div class="stat-container">
        <div class="special-stats">
          <i class="fas fa-star"></i><i class="fas fa-shield-alt"></i>
        </div>
        <div class="stat sp-def"><%= @pokemon.special_defense %></div>
      </div>
      <div class="stat-container">
        <div class="special-stats">
          <i class="fas fa-paw"></i><i class="fas fa-tachometer-alt"></i>
        </div>
        <div class="stat speed"><%= @pokemon.speed %></div>
      </div>
    </div>
  </div>
  <div id="evolution-content">
    <% if !@evolution_chain[:second].present? %>
      <div id="cant-evolve-text">Sadly, this Pokemon is the only link in its evolution chain 😞</div>
    <% end %>
    <div id="chain-header">Evolution Chain:</div>
    <% @evolution_chain.each do |level, pokemons_in_level| %>
      <% if pokemons_in_level.present? %>
        <% unless level == :first %>
          <div class="can-evolve-text">Which can potentially evolve to:</div>
        <% end %>
        <div class="column column-<%= level.to_s %>">
          <% pokemons_in_level.each do |pokemon| %>
            <% @pokemon = pokemon %>
            <%= render 'partials/card' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div id="js-page-identifier" data-current-page="index"></div>

<div class="content">
  <% @pokemons.each do |pokemon| %>
    <% @pokemon = pokemon %>
    <%= render "partials/card" %>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<div id="js-page-identifier" data-current-page="show"></div>

<%= render 'partials/showcase' %>